### ISSUE TITLE
Rename the plugin to "Ultra IDs"

### ISSUE THREAD

**Issue by versusbassz** [versusbassz/ultra-ids#10]
Just visually (+ some tech changes like namespace) because we are forever with `hh-sortable` plugin slug :(

## todo
- [x] change the slug of the github repo: `versusbassz/sortable-id-columns -> versusbassz/ultra-ids`
- [x] change the name of the plugin in the codebase: `HH sortable ID columns -> Ultra IDs`
- [x] change the PHP-namespace: `IdColumns -> UltraIds`
- [ ] update the info in the description of the github repo
- [ ] update info in readme.txt
- [ ] update info in the entry PHP-file (description)

## Docs
- https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#can-i-change-my-plugins-name-after-its-approved
