### ISSUE TITLE
IDs to Network Users and Network Websites/Blogs

### ISSUE THREAD

**Issue by versusbassz** [versusbassz/ultra-ids#7]
- https://wordpress.org/support/topic/multisite-network-user-ids/
- https://wordpress.org/plugins/reveal-ids-for-wp-admin-25/#developers
    - [the code](https://plugins.trac.wordpress.org/browser/reveal-ids-for-wp-admin-25/trunk/reveal-ids-for-wp-admin-25.php)

## Docs
- https://developer.wordpress.org/cli/commands/plugin/activate/
    - `--network` param
- https://developer.wordpress.org/cli/commands/core/multisite-install/
    - `--skip-config` param 
- https://developer.wordpress.org/cli/commands/core/multisite-convert/ --- install is better
- https://wordpress.org/support/article/create-a-network/ --- main documentation about Multisite 
- https://developer.wordpress.org/cli/commands/network/ --- what is it?
- https://getcomposer.org/doc/06-config.md#platform --- as usual
- https://stackoverflow.com/questions/13960514/how-to-adapt-my-plugin-to-multisite/ --- the great intro to multisite details

## Misc
- https://github.com/wodby/nginx/blob/master/templates/presets/wordpress.conf.tmpl
- sunrise.php
    - https://docs.wpvip.com/technical-references/multisites/sunrise-php/
    - https://github.com/markoheijnen/wordpress-mu-domain-mapping/blob/master/sunrise.php
    - https://gist.github.com/mhawksey/49f03991119c465cc33a
- https://kinsta.com/blog/wordpress-multisite/
- wp_home for multisite
    - https://stackoverflow.com/questions/12958123/override-wp-siteurl-and-wp-home-for-wordpress-multisite
    - https://stackoverflow.com/questions/12954788/team-development-of-a-wordpress-site
```php
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', true);
```

## TODO
- [x] e2e-tests can't connect to the test site
    - ms_not_installed() -> wp-settings/ms-settings.php -> i need sunrise.php (OMG)
- [x] decide something about `composer.json -> config -> platform`
- [x] recheck situation when the plugin isn't active network wide but active on 1st (main) site and affect network pages (seems like it's by design)
    - its a feature, see `wp_get_active_and_valid_plugins()`

**Comment by versusbassz** [comment]
Done. The good work.
