### ISSUE TITLE
Display entity ID in the admin bar

### ISSUE THREAD

**Issue by versusbassz** [versusbassz/ultra-ids#9]
at least on the frontend
~~but maybe wp-admin also fit~~ (no, we don't need wp-admin here, because it almost doesn't make sense since user can at least copy the ID from a link)

## TODO
**v4.0.0**
- [x] posts
- [x] terms
- [x] authors
- [ ] capabilities: use meta-capabilities to check certain

**future**
- [ ] copy to clipboard button
- [ ] tooltip with useful content
    - Examples
        - `Attachment \n Table: posts \n Post type id: attachment`
        - `User \n Table: users`
        - `Tag \n Table: terms \n Taxonomy id: post_tag`
    - show `table` and `type` fields only for administrators in single mode and super-admins in Multisite
